TOPDIR = ..
MKDIR = $(TOPDIR)/Make

EXES = sombrero1 \
	   sombrero2 \
	   sombrero3 \
	   sombrero5 \
	   sombrero4 \
	   sombrero6 \
	   sombrero3max \
	   sombrero3fmax

clean::
	rm -fr su2 su2adj su3 su3sym sp4 sp4adj su3max su3fmax
	rm -f *~
	rm -f *.o

include $(MKDIR)/MkRules
