TOPDIR = ..
MKDIR = $(TOPDIR)/Make

LIBDIRS = Inverters Random Utils Random MaxelerInterface Memory Update IO Geometry Error

clean::
	rm -fr su2 su2adj su3 su3sym sp4 sp4adj su3max

include $(MKDIR)/MkRules

